### ISSUE TITLE
bug:Unknown node type JSXElement.

### ISSUE THREAD

**Issue by p0sec** [estools/estraverse#103]
/Users/p0/work/code/stc-node/node_modules/_estraverse@4.3.0@estraverse/estraverse.js:454
                        throw new Error('Unknown node type ' + nodeType + '.');
                        ^

Error: Unknown node type JSXElement.
    at Controller.traverse (/Users/p0/work/code/stc-node/node_modules/_estraverse@4.3.0@estraverse/estraverse.js:454:31)
    at Object.traverse (/Users/p0/work/code/stc-node/node_modules/_estraverse@4.3.0@estraverse/estraverse.js:646:27)
    at HashMap.<anonymous> (/Users/p0/work/code/stc-node/lib/primaryengine.js:406:20)
    at HashMap.forEach (/Users/p0/work/code/stc-node/node_modules/_hashmap@2.4.0@hashmap/hashmap.js:171:10)
    at HashMap.proto.(anonymous function) [as forEach] (/Users/p0/work/code/stc-node/node_modules/_hashmap@2.4.0@hashmap/hashmap.js:201:7)
    at collectRouterConfigs (/Users/p0/work/code/stc-node/lib/primaryengine.js:405:24)
    at Object.analyze (/Users/p0/work/code/stc-node/lib/primaryengine.js:66:5)
    at Object.<anonymous> (/Users/p0/work/code/stc-node/index.js:116:15)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)

**Comment by zdm** [comment]
Did you solved this problem?
I have similar case.
