### ISSUE TITLE
4.1.0 -> 4.1.1 update breaks eslint

### ISSUE THREAD

**Issue by ikr** [estools/estraverse#61]
I'm not completely sure if the problem is with estraverse or eslint, but the fact is that eslint works just fine for us over estraverse 4.1.0, bur over estraverse 4.1.1 it does that:

```
> browser-app@4.1.0 lint /home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app
> eslint ./src ./index.js ./tests


/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/estraverse/estraverse.js:411
                current = candidates.length;
                                    ^
TypeError: Cannot read property 'length' of undefined
    at Controller.traverse (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/estraverse/estraverse.js:411:37)
    at EventEmitter.module.exports.api.verify (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/eslint.js:779:24)
    at processText (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli-engine.js:221:27)
    at processFile (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli-engine.js:258:18)
    at executeOnFile (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli-engine.js:604:23)
    at Array.forEach (native)
    at /home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli-engine.js:630:49
    at Array.forEach (native)
    at CLIEngine.executeOnFiles (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli-engine.js:626:18)
    at Object.cli.execute (/home/gitlab-runner/builds/be2d88b2/0/stc-b2b/browser-app/node_modules/eslint/lib/cli.js:159:95)
```

**Comment by michaelficarra** [comment]
You didn't really give me much to go on. You can check out the diff here: https://github.com/estools/estraverse/compare/4.1.0...4.1.1.

Closing until a repro is posted.

**Comment by ikr** [comment]
True, sorry. Seems it's somehow related to npm. Clean install with npm 2 results in a fully functional eslint + estraverse, but clean install with npm 3 fails as noted above.

**Comment by ikr** [comment]
Alright, so if someone else bothers you again about that, you can relate them to https://github.com/npm/npm/issues/9663 

Have a nice day!
